document.writeln("<center>")
document.writeln("<hr width=600 color=black>")
document.writeln("<h1>SMK NEGERI 1 CIAMIS</h1>")
document.writeln("<h2>TEKNIK KOMPUTER DAN INFORMATIKA</h2>")
document.writeln("<h3>JURUSAN REKAYASA PERANGKAT LUNAK</h3>")
document.writeln("<hr width=600 color=black")
document.writeln("</center>")